//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tarsalgo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("tarsalgo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9 1 2 be
        ///9 1 9 be
        ///9 3 15 be
        ///9 5 9 ki
        ///9 8 15 ki
        ///9 8 20 be
        ///9 8 26 be
        ///9 13 4 be
        ///9 13 26 ki
        ///9 14 5 be
        ///9 14 20 ki
        ///9 16 4 ki
        ///9 18 2 ki
        ///9 18 5 ki
        ///9 19 25 be
        ///9 20 35 be
        ///9 21 11 be
        ///9 21 25 ki
        ///9 21 4 be
        ///9 21 6 be
        ///9 22 2 be
        ///9 22 23 be
        ///9 23 4 ki
        ///9 24 28 be
        ///9 24 35 ki
        ///9 25 11 ki
        ///9 25 23 ki
        ///9 26 16 be
        ///9 26 6 ki
        ///9 26 9 be
        ///9 27 35 be
        ///9 28 9 ki
        ///9 28 28 ki
        ///9 29 16 ki
        ///9 30 35 ki
        ///9 31 37 be
        ///9 34 2 ki
        ///9 34 21 be
        ///9 35 37 ki
        ///9 36 21 ki
        ///9 38 31 be
        ///9 41 5 be
        ///9 41 23 be
        ///9 41 31 ki
        ///9 42 4 b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ajto {
            get {
                return ResourceManager.GetString("ajto", resourceCulture);
            }
        }
    }
}
